export const COLOR_PALETTE = [
    { hex: '#000000', token: 'neutralBlack', usage: 'Primary text, icons, and high-contrast surfaces' },
    { hex: '#00000000', token: 'transparent', usage: 'Fully transparent for invisible backgrounds' },
    { hex: '#00000026', token: 'shadowSubtleBlack', usage: 'Soft shadow used on elevated cards' },
    { hex: '#00000080', token: 'overlayDimBlack', usage: 'Dimmed modal overlay backdrop' },
    { hex: '#0000FF', token: 'authGoogleBlue', usage: 'Google social auth accent' },
    { hex: '#004085', token: 'notesInfoDeepBlue', usage: 'Empty notes education text' },
    { hex: '#0066CC', token: 'brandPrimaryBlue', usage: 'Primary links and interactive text' },
    { hex: '#007AFF', token: 'uiSpinnerBlue', usage: 'Fallback loading indicator color' },
    { hex: '#059669', token: 'brandSuccessGreen', usage: 'Success state accents' },
    { hex: '#111111', token: 'textHighContrast', usage: 'High-contrast heading text' },
    { hex: '#17306BFF', token: 'legacyDeepNavy', usage: 'Legacy palette deep navy tone' },
    { hex: '#1C1C1E', token: 'dsTextBase', usage: 'Design system primary text' },
    { hex: '#1DB954', token: 'dsSuccessGreen', usage: 'Design system success token' },
    { hex: '#1F1F1F', token: 'onboardingTitleGraphite', usage: 'Onboarding copy headline color' },
    { hex: '#1F2538', token: 'notesBodyCharcoal', usage: 'Note input body text' },
    { hex: '#22C55E', token: 'uiSuccessGreen', usage: 'Success modal check icon' },
    { hex: '#282525', token: 'scheduleModalTimeInk', usage: 'Schedule modal time display text' },
    { hex: '#282525FF', token: 'onboardingTitleDeepInk', usage: 'Onboarding welcome heading' },
    { hex: '#28304A59', token: 'notesPlaceholderSlate', usage: 'Note input placeholder text' },
    { hex: '#28A745', token: 'notesSuccessGreen', usage: 'Success messaging inside notes' },
    { hex: '#2B2FC7', token: 'dsPrimaryDarkIndigo', usage: 'Design system primary dark token' },
    { hex: '#2F2D31', token: 'legacyStone', usage: 'Legacy palette deep stone' },
    { hex: '#31BBCC', token: 'legacyTeal', usage: 'Legacy teal accent' },
    { hex: '#333333', token: 'textMediumContrast', usage: 'Medium emphasis text' },
    { hex: '#3C2A2BFF', token: 'legacyMaroon', usage: 'Legacy maroon brand tone' },
    { hex: '#444444', token: 'textMutedGraphite', usage: 'Muted explanatory text' },
    { hex: '#444548FF', token: 'legacySlate', usage: 'Legacy dark slate' },
    { hex: '#494848FF', token: 'remindersDescriptionGray', usage: 'Reminder card description text' },
    { hex: '#495057', token: 'textSlate', usage: 'Slate body copy in notes and reminders' },
    { hex: '#4B4242FF', token: 'onboardingSubtitleMulberry', usage: 'Onboarding subtitle tone' },
    { hex: '#4B4DED', token: 'dsPrimaryIndigo', usage: 'Design system primary brand color' },
    { hex: '#4C6EF5', token: 'calendarSelectedBlue', usage: 'Calendar selected day fill' },
    { hex: '#4D3131', token: 'calendarMonthDeepBrown', usage: 'Calendar month label text' },
    { hex: '#542626', token: 'calendarDayDeepMaroon', usage: 'Calendar default day text' },
    { hex: '#555555', token: 'textSoftGraphite', usage: 'Soft contrast captions' },
    { hex: '#56A8FF73', token: 'noteCardShadowBlue', usage: 'Note card elevated shadow' },
    { hex: '#5C5252FF', token: 'settingsIconMauve', usage: 'Settings chevron icon' },
    { hex: '#5C5C5C73', token: 'buttonDisabledText', usage: 'Disabled button label tint' },
    { hex: '#65676BFF', token: 'legacyCharcoal', usage: 'Legacy charcoal neutral' },
    { hex: '#666666', token: 'textNeutral', usage: 'Neutral supporting text' },
    { hex: '#6A4D50FF', token: 'notesPlusIconPlum', usage: 'Add note floating action icon' },
    { hex: '#6B6B74', token: 'dsTextMuted', usage: 'Design system muted text token' },
    { hex: '#6C757D', token: 'notesMutedSlate', usage: 'Secondary text in notes list' },
    { hex: '#6E6E6E1A', token: 'buttonDisabledBorder', usage: 'Disabled button border stroke' },
    { hex: '#74777B', token: 'legacySlateLight', usage: 'Legacy light slate neutral' },
    { hex: '#752A2A', token: 'calendarTextMaroon', usage: 'Calendar unscheduled text' },
    { hex: '#808080', token: 'textNeutralGray', usage: 'Generic neutral gray text' },
    { hex: '#856404', token: 'alertTextAmber', usage: 'Warning messaging text' },
    { hex: '#888888', token: 'textSubtle', usage: 'Low emphasis metadata text' },
    { hex: '#8CACE840', token: 'buttonShadowBlue', usage: 'Floating action button shadow' },
    { hex: '#9CA3AF', token: 'constNeutralGray', usage: 'Constants module neutral gray' },
    { hex: '#A28787', token: 'calendarWeekdayMauve', usage: 'Calendar weekday header text' },
    { hex: '#B8E0E7', token: 'legacyIceBlue', usage: 'Legacy light cyan tone' },
    { hex: '#BEE5EB', token: 'notesBorderSky', usage: 'Notes list highlight border' },
    { hex: '#C1D0E0FF', token: 'radioOutlineBlue', usage: 'Radio button outline background' },
    { hex: '#C3B3B2FF', token: 'settingsBorderBlush', usage: 'Settings row border' },
    { hex: '#CAA4A4', token: 'calendarDisabledRose', usage: 'Calendar disabled day text' },
    { hex: '#CCCCCC', token: 'scheduleBorderNeutral', usage: 'Schedule modal time picker border' },
    { hex: '#CDD2DC', token: 'legacyCloud', usage: 'Legacy cool gray tone' },
    { hex: '#D35555', token: 'calendarActiveCrimson', usage: 'Calendar active session fill' },
    { hex: '#D8E6EA', token: 'legacyMist', usage: 'Legacy mist blue' },
    { hex: '#DBE0E4', token: 'backgroundGradientLight', usage: 'Background gradient mid stop' },
    { hex: '#DC2626', token: 'brandDangerRed', usage: 'Danger emphasis and error states' },
    { hex: '#DDDDDD', token: 'dividerNeutral', usage: 'Login divider rule' },
    { hex: '#E1E6EA', token: 'backgroundGradientNeutral', usage: 'Background gradient light stop' },
    { hex: '#E23D3D', token: 'calendarAlertRed', usage: 'Calendar alert foreground' },
    { hex: '#E23D3D21', token: 'calendarAlertTint', usage: 'Calendar alert badge fill' },
    { hex: '#E23D3D4C', token: 'calendarAlertBorder', usage: 'Calendar alert badge border' },
    { hex: '#E2E6EA', token: 'legacySurface', usage: 'Legacy surface background' },
    { hex: '#E5E6EA', token: 'dsBorder', usage: 'Design system border token' },
    { hex: '#E5E7EB', token: 'constBorder', usage: 'Constants module border gray' },
    { hex: '#E7F3FF', token: 'notesPreviewSky', usage: 'Note preview modal backdrop' },
    { hex: '#E8F4FD', token: 'brandLightBlue', usage: 'Brand soft blue background' },
    { hex: '#E9ECEF', token: 'cardBorderGray', usage: 'Card outline gray' },
    { hex: '#EEF3F7FF', token: 'scheduleSurface', usage: 'Schedule modal surface' },
    { hex: '#F0C7CAFF', token: 'gradientRoseMid', usage: 'Header gradient mid stop' },
    { hex: '#F26C6C', token: 'dsAccentCoral', usage: 'Design system accent' },
    { hex: '#F5C3C308', token: 'buttonDisabledFill', usage: 'Disabled button background tint' },
    { hex: '#F5F5F7', token: 'dsSurfaceMuted', usage: 'Design system muted surface' },
    { hex: '#F6B7B9FF', token: 'gradientRoseLight', usage: 'Header gradient light stop' },
    { hex: '#F7A2A4', token: 'calendarScheduledBlush', usage: 'Calendar scheduled session fill' },
    { hex: '#F8F9FA', token: 'surfaceAlt', usage: 'Alternate surface background' },
    { hex: '#F8FBFF', token: 'reminderHighlight', usage: 'Reminder card highlight fill' },
    { hex: '#F9F9F9', token: 'authBackground', usage: 'Auth screen background' },
    { hex: '#FAA9A9', token: 'calendarBorderBlush', usage: 'Calendar scheduled border' },
    { hex: '#FDA6A6', token: 'calendarDraftBlush', usage: 'Calendar unscheduled fill' },
    { hex: '#FEE2E2', token: 'brandDangerTint', usage: 'Danger soft background' },
    { hex: '#FF0000', token: 'authAppleSpinnerRed', usage: 'Apple auth loading indicator' },
    { hex: '#FF4D4F', token: 'dsDangerRed', usage: 'Design system danger token' },
    { hex: '#FF777C', token: 'gradientRoseDeep', usage: 'Header gradient deep stop' },
    { hex: '#FF7B9B', token: 'inputSelectionPink', usage: 'Notes text selection color' },
    { hex: '#FFA83D', token: 'dsWarningAmber', usage: 'Design system warning token' },
    { hex: '#FFDCDCE6', token: 'notesBadgeRose', usage: 'Latest note badge fill' },
    { hex: '#FFEEBA', token: 'alertBorderSoft', usage: 'Warning container border' },
    { hex: '#FFF3CD', token: 'alertBackgroundSoft', usage: 'Warning container background' },
    { hex: '#FFFFFF', token: 'neutralWhite', usage: 'Primary surface and text contrast' },
    { hex: '#FFFFFF36', token: 'cardBorderSoft', usage: 'Translucent card border' },
    { hex: '#FFFFFF38', token: 'cardSurfaceTranslucent', usage: 'Translucent card fill' },
    { hex: '#FFFFFF4A', token: 'cardSurfaceTint', usage: 'Glassmorphism card tint' },
    { hex: '#FFFFFF78', token: 'cardSurfacePressed', usage: 'Pressed card highlight' },
    { hex: '#FFFFFF99', token: 'reminderFooterGlass', usage: 'Reminder footer glass fill' },
    { hex: '#FFFFFFE6', token: 'loadingBackdrop', usage: 'Full screen loading scrim' },
] as const;

export type ColorToken = typeof COLOR_PALETTE[number]['token'];

export const Colors: Record<ColorToken, string> = COLOR_PALETTE.reduce((acc, { token, hex }) => {
    acc[token] = hex;
    return acc;
}, {} as Record<ColorToken, string>);

export const Palette = {
    darkGreen: Colors.legacyTeal,
    greenMedium: Colors.legacyIceBlue,
    greenLight: Colors.legacyMist,
    greyLight: Colors.legacySurface,
    greyDark: Colors.legacyCloud,
    greyDarkest2: Colors.legacySlate,
    greyDarkest: Colors.legacyCharcoal,
    greyDarkestLight: Colors.legacySlateLight,
    black: Colors.neutralBlack,
    dark: Colors.legacyStone,
    white: Colors.neutralWhite,
    darkBlue: Colors.legacyDeepNavy,
    maroon: Colors.legacyMaroon,
};
