/**
 * The dark theme, assembled from designs-night. The comments explaining each
 * value live there, beside the value.
 */

import { PALETTE } from './designs-colors';
import { CALENDAR_BACKDROP_BASE_LOCATIONS, CALENDAR_BACKDROP_GLOW_LOCATIONS } from './designs-gradients';
import {
    NIGHT_ACCENT,
    NIGHT_ACCENT_SCREEN,
    NIGHT_AURA,
    NIGHT_CALENDAR_BACKDROP_BASE,
    NIGHT_CALENDAR_BACKDROP_GLOW,
    NIGHT_CALENDAR_MONTH,
    NIGHT_CALENDAR_SHEET,
    NIGHT_CHART,
    NIGHT_GLASS,
    NIGHT_GRADIENT,
    NIGHT_GREEN_PANEL,
    NIGHT_GROUND,
    NIGHT_GROUND_FADE,
    NIGHT_HAIRLINE,
    NIGHT_INK,
    NIGHT_LINK,
    NIGHT_LINK_PRESSED,
    NIGHT_MARK,
    NIGHT_MARK_SWEEP,
    NIGHT_PAPER,
    NIGHT_RADIO,
    NIGHT_RED,
    NIGHT_RULE,
    NIGHT_SOLID,
    NIGHT_SWEEP,
    NIGHT_STATUS,
    NIGHT_SURFACE,
} from './designs-night';
import type { Theme } from './designs-theme-shape';

export const darkTheme: Theme = {
    scheme: 'dark',
    statusBar: 'light-content',
    ink: NIGHT_INK,
    ground: {
        gradient: NIGHT_GRADIENT,
        base: NIGHT_GROUND,
        fade: NIGHT_GROUND_FADE,
    },
    surface: {
        card: NIGHT_SURFACE.card,
        cardBorder: NIGHT_SURFACE.cardBorder,
        cardEdge: NIGHT_SURFACE.cardEdge,
        cardShadow: NIGHT_SURFACE.cardShadow,
        cardShadowOpacity: 0.9,
        shadowOffset: { width: 8, height: 12 },
        shadowRadius: 24,
        frostedShadow: NIGHT_SURFACE.frostedShadow,
        gradientCardShadow: NIGHT_SURFACE.gradientCardShadow,
        soft: NIGHT_SURFACE.soft,
        medium: NIGHT_SURFACE.medium,
        row: NIGHT_SURFACE.row,
        rowBorder: NIGHT_SURFACE.rowBorder,
        rowGroup: NIGHT_SURFACE.rowGroup,
        rowGroupBorder: NIGHT_SURFACE.rowGroupBorder,
        groove: NIGHT_SURFACE.groove,
        sheet: NIGHT_SURFACE.sheet,
        sheetTint: NIGHT_SURFACE.sheetTint,
        readingCard: NIGHT_SURFACE.readingCard,
        chip: NIGHT_SURFACE.chip,
        cardHighlight: NIGHT_SURFACE.cardHighlight,
        lightRim: NIGHT_SURFACE.lightRim,
        modal: NIGHT_SURFACE.modal,
        scrim: NIGHT_SURFACE.scrim,
        sheetCard: NIGHT_SURFACE.sheetCard,
        sheetCardBorder: NIGHT_SURFACE.sheetCardBorder,
        field: NIGHT_SURFACE.field,
        fieldBorder: NIGHT_SURFACE.fieldBorder,
        fieldBorderFocused: NIGHT_SURFACE.fieldBorderFocused,
        disabledLight: NIGHT_SURFACE.disabledLight,
        spinnerWell: NIGHT_SURFACE.spinnerWell,
        tinted: NIGHT_SURFACE.tinted,
        tintedBorder: NIGHT_SURFACE.tintedBorder,
        tintCard: NIGHT_SURFACE.tintCard,
        tintCardBorder: NIGHT_SURFACE.tintCardBorder,
    },
    glass: {
        tint: 'dark',
        background: NIGHT_SURFACE.glass,
        highlight: NIGHT_GLASS.highlight,
        rim: NIGHT_GLASS.rim,
        rimOpacity: NIGHT_GLASS.rimOpacity,
        shade: NIGHT_GLASS.shade,
        disabledLabel: NIGHT_INK.quaternary,
    },
    radio: NIGHT_RADIO,
    shadow: PALETTE.neutral.black,
    solid: NIGHT_SOLID,
    link: {
        color: NIGHT_LINK,
        pressed: NIGHT_LINK_PRESSED,
        bright: NIGHT_LINK,
        brightPressed: NIGHT_LINK_PRESSED,
    },
    accent: {
        mark: NIGHT_ACCENT.mark,
        markSurface: NIGHT_ACCENT.markSurface,
        markInk: NIGHT_ACCENT.markInk,
        ring: NIGHT_MARK,
        sweep: NIGHT_SWEEP,
    },
    chosen: {
        fill: NIGHT_ACCENT.chosenFill,
        ink: NIGHT_INK.primary,
        inkBright: NIGHT_INK.primary,
        inkBrightest: NIGHT_INK.secondary,
        border: 'hsla(0, 0%, 100%, 0.28)',
        ring: NIGHT_MARK,
        mark: NIGHT_MARK_SWEEP,
        check: NIGHT_SOLID.background,
        iconDisc: 'hsla(0, 0%, 100%, 0.10)',
        // The original's black badge, with grey type on it: the one object on
        // a chosen card that stays a dark pill.
        trialFill: NIGHT_SOLID.background,
        trialText: NIGHT_INK.secondary,
    },
    emphasis: {
        panel: NIGHT_ACCENT.panel,
        rule: NIGHT_RULE,
        ink: NIGHT_INK.primary,
        inkSecondary: NIGHT_INK.secondary,
        inkMuted: NIGHT_INK.secondary,
    },
    accentScreen: {
        ground: NIGHT_ACCENT_SCREEN.ground,
        textPrimary: NIGHT_ACCENT_SCREEN.textPrimary,
        textSecondary: NIGHT_ACCENT_SCREEN.textSecondary,
        card: NIGHT_ACCENT_SCREEN.card,
        cardBorder: NIGHT_ACCENT_SCREEN.cardBorder,
        cardEdge: NIGHT_ACCENT_SCREEN.cardEdge,
        glow: NIGHT_SWEEP,
    },
    status: NIGHT_STATUS,
    red: NIGHT_RED,
    aura: NIGHT_AURA,
    paper: NIGHT_PAPER,
    trialBadge: NIGHT_GREEN_PANEL,
    calendar: {
        month: NIGHT_CALENDAR_MONTH,
        backdrop: {
            base: NIGHT_CALENDAR_BACKDROP_BASE,
            baseLocations: CALENDAR_BACKDROP_BASE_LOCATIONS,
            glow: NIGHT_CALENDAR_BACKDROP_GLOW,
            glowLocations: CALENDAR_BACKDROP_GLOW_LOCATIONS,
            blurTint: 'dark',
            blurIntensity: 20,
        },
        sheet: NIGHT_CALENDAR_SHEET,
    },
    chart: NIGHT_CHART,
    hairline: NIGHT_HAIRLINE,
    hairlineFaint: 'hsla(0, 0%, 100%, 0.08)',
    navigation: {
        background: NIGHT_GROUND,
        card: NIGHT_SURFACE.sheet,
        text: NIGHT_INK.primary,
        border: NIGHT_SURFACE.cardBorder,
    },
};

